name: ChatCo
version: 1.0
main: eu.felicianware.chatCo.ChatCo
api-version: 1.20
folia-supported: true
author: LachCrafter
commands:
  msg:
    description: Send a private message to a player.
    usage: /<command> <player> <message>
    aliases: [pm, w]
  ignore:
    description: Ignore or unignore a player.
    usage: /<command> <player>
  ignorelist:
    description: Lists all players you are currently ignoring.
    usage: /<command>
  r:
    description: Reply to the last player.
    usage: /r <message>
    aliases: [ reply ]