name: ChatCo
version: 1.0
main: eu.felicianware.chatCo.ChatCo
author: LachCrafter
api-version: 1.21
folia-supported: true
commands:
  msg:
    description: Send a private message to a player.
    usage: /<command> <player> <message>
    aliases: [pm, w]
  ignore:
    description: Ignore or unignore a player.
    usage: /<command> <player>
  ignorelist:
    description: Lists all players you are currently ignoring.
    usage: /<command>
  r:
    description: Sends a message the last player.
    usage: /<command> <message>
    aliases: [reply]
  coreload:
    description: Reload the configuration
    usage: /coreload